In [1]:
import numpy as np


In [2]:
a = np.array([1,2])
b = np.array([2,1])


In [3]:
z = np.log(a) 
print(z)

[0.         0.69314718]


In [4]:
z = np.exp(a)
print(z)

[2.71828183 7.3890561 ]


In [5]:
z = np.sqrt(a)
print(z)


[1.         1.41421356]


In [6]:
z = np.dot(a,b)
z = a.dot(b)
print(z)

4


In [7]:
z = np.linalg.norm(a)
print(z)


2.23606797749979


In [8]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))#ANGLE B/W VECTORS
print(cosangle)

0.7999999999999998


In [9]:
angle = np.arccos(cosangle)
print(angle)   #ANGLE IN RADIAN

0.6435011087932847


In [10]:
a = np.matrix([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
print(a[0,0])

1


In [12]:
x = np.array(a)
print(x)


[[1 2 3]
 [4 5 6]]


In [13]:
print(x.T) #TRANSPOSE


[[1 4]
 [2 5]
 [3 6]]


In [14]:
z = np.zeros(5)
print(z)


[0. 0. 0. 0. 0.]


In [15]:
m = np.zeros((2,2))


In [16]:
print(m)

[[0. 0.]
 [0. 0.]]


In [17]:
o = np.ones((3,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
r = np.random.random((2,2))
print(r)

[[0.93089847 0.2696525 ]
 [0.78568953 0.59205304]]


In [20]:
h = np.random.randn(2,2)
print(h)

[[ 0.76421736 -1.10566079]
 [ 0.06908907  0.27387317]]


In [21]:
print(h.mean())

0.0003797014371280244


In [22]:
print(h.var())


0.47157329905624756


In [23]:
p = np.array([[1,2,3],[2,2,1],[6,7,9]])
q = np.array([[4,5],[6,7],[6,8]])


In [24]:
r = p.dot(q)
print(r)

[[ 34  43]
 [ 26  32]
 [120 151]]


In [25]:
pinv = np.linalg.inv(p)
print(pinv)


[[-1.57142857 -0.42857143  0.57142857]
 [ 1.71428571  1.28571429 -0.71428571]
 [-0.28571429 -0.71428571  0.28571429]]


In [26]:
correct = p.dot(pinv)
print(correct)


[[ 1.00000000e+00 -4.44089210e-16  1.11022302e-16]
 [-1.66533454e-16  1.00000000e+00  1.66533454e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [27]:
d = np.linalg.det(p)
print(d)


-7.000000000000004


In [28]:
di = np.diag(p)
print(di)

[1 2 9]


In [29]:
x = np.diag([1,2,3,4])
print(x)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [30]:
x = np.trace(x)
print(x)
    

10
